-- ==========================================
-- FULL DEMO DATA INSERTS (RICH DATA)
-- ==========================================

SET FOREIGN_KEY_CHECKS=0;

INSERT IGNORE INTO `configuracion_centro` (`idConfig`, `nombreCentro`, `codigoCentro`, `cursoEscolar`, `ciudadCentro`, `feature_ra_ce`, `feature_fp_dual`) VALUES (1, 'Centro FP Tech Academy', '28012345', '2025-2026', 'Madrid', 1, 1);
INSERT IGNORE INTO `directores` (`idDirector`, `nombreDirector`, `emailDirector`, `dniDirector`, `telefonoDirector`) VALUES (1, 'Ana Martínez', 'admin@aulapro.com', '11111111A', '600111111');
INSERT IGNORE INTO `secretarias` (`idSecretaria`, `nombreSecretaria`, `emailSecretaria`, `password`, `activoSecretaria`, `must_change_password`) VALUES (1, 'Laura Gómez', 'laura@aulapro.com', '$2y$10$9nwmzvOe4muwQ9jM5Ryc7.bmaA3Gipm7S4Wnj2S1oiDPnRo1JNcvu', 1, 0);
INSERT IGNORE INTO `niveles` (`idNivel`, `nombreNivel`) VALUES (1, 'Grado Medio');
INSERT IGNORE INTO `niveles` (`idNivel`, `nombreNivel`) VALUES (2, 'Grado Superior');
INSERT IGNORE INTO `ciclos` (`idCiclo`, `nombreCiclo`, `abreviaturaCiclo`, `precioCiclo`, `idNivel`, `activo`) VALUES (1, 'Desarrollo de Aplicaciones Web', 'DAW', 2500.0, 2, 1);
INSERT IGNORE INTO `ciclos` (`idCiclo`, `nombreCiclo`, `abreviaturaCiclo`, `precioCiclo`, `idNivel`, `activo`) VALUES (2, 'Sistemas Microinformáticos y Redes', 'SMR', 1800.0, 1, 1);
INSERT IGNORE INTO `ciclos` (`idCiclo`, `nombreCiclo`, `abreviaturaCiclo`, `precioCiclo`, `idNivel`, `activo`) VALUES (3, 'Desarrollo de Aplicaciones Multiplataforma', 'DAM', 2600.0, 2, 1);
INSERT IGNORE INTO `ciclos` (`idCiclo`, `nombreCiclo`, `abreviaturaCiclo`, `precioCiclo`, `idNivel`, `activo`) VALUES (4, 'Administración de Sistemas Informáticos en Red', 'ASIR', 2400.0, 2, 1);
INSERT IGNORE INTO `ciclos` (`idCiclo`, `nombreCiclo`, `abreviaturaCiclo`, `precioCiclo`, `idNivel`, `activo`) VALUES (5, 'Marketing y Publicidad', 'MKT', 2100.0, 2, 1);
INSERT IGNORE INTO `cursos_academicos` (`idCurso`, `idCiclo`) VALUES (1, 1);
INSERT IGNORE INTO `cursos_academicos` (`idCurso`, `idCiclo`) VALUES (2, 1);
INSERT IGNORE INTO `cursos_academicos` (`idCurso`, `idCiclo`) VALUES (3, 2);
INSERT IGNORE INTO `cursos_academicos` (`idCurso`, `idCiclo`) VALUES (4, 3);
INSERT IGNORE INTO `cursos_academicos` (`idCurso`, `idCiclo`) VALUES (5, 4);
INSERT IGNORE INTO `modulos` (`idModulo`, `nombreModulo`, `codigoModulo`, `horasMaximas`, `idCiclo`, `idCurso`, `tipoModulo`, `creditosECTS`) VALUES (1, 'Programación', 'PROG', 250, 1, 1, 'Específico', 10);
INSERT IGNORE INTO `modulos` (`idModulo`, `nombreModulo`, `codigoModulo`, `horasMaximas`, `idCiclo`, `idCurso`, `tipoModulo`, `creditosECTS`) VALUES (2, 'Bases de Datos', 'BBDD', 200, 1, 1, 'Específico', 8);
INSERT IGNORE INTO `modulos` (`idModulo`, `nombreModulo`, `codigoModulo`, `horasMaximas`, `idCiclo`, `idCurso`, `tipoModulo`, `creditosECTS`) VALUES (3, 'Desarrollo Web Cliente', 'DWEC', 120, 1, 2, 'Específico', 6);
INSERT IGNORE INTO `modulos` (`idModulo`, `nombreModulo`, `codigoModulo`, `horasMaximas`, `idCiclo`, `idCurso`, `tipoModulo`, `creditosECTS`) VALUES (4, 'Sistemas Operativos', 'SOM', 150, 2, 3, 'Específico', 5);
INSERT IGNORE INTO `modulos` (`idModulo`, `nombreModulo`, `codigoModulo`, `horasMaximas`, `idCiclo`, `idCurso`, `tipoModulo`, `creditosECTS`) VALUES (5, 'Entornos de Desarrollo', 'ENDES', 90, 3, 4, 'Específico', 4);
INSERT IGNORE INTO `modulos` (`idModulo`, `nombreModulo`, `codigoModulo`, `horasMaximas`, `idCiclo`, `idCurso`, `tipoModulo`, `creditosECTS`) VALUES (6, 'Redes de Área Local', 'REDES', 180, 4, 5, 'Específico', 8);
INSERT IGNORE INTO `profesores` (`idProfesor`, `nombreProfesor`, `emailProfesor`, `dniProfesor`, `esTutor`, `idCicloTutor`, `telefonoProfesor`, `fechaNacimientoProfesor`, `direccionProfesor`, `ciudadProfesor`, `codigoPostalProfesor`) VALUES (1, 'Carlos López', 'carlos@aulapro.com', '22222222B', 1, 1, '611222333', '1980-05-15', 'Calle Mayor 1', 'Madrid', '28001');
INSERT IGNORE INTO `profesores` (`idProfesor`, `nombreProfesor`, `emailProfesor`, `dniProfesor`, `esTutor`, `telefonoProfesor`, `fechaNacimientoProfesor`, `direccionProfesor`, `ciudadProfesor`, `codigoPostalProfesor`) VALUES (2, 'María Fernández', 'maria@aulapro.com', '33333333C', 0, '611222444', '1985-08-20', 'Gran Vía 10', 'Madrid', '28002');
INSERT IGNORE INTO `profesores` (`idProfesor`, `nombreProfesor`, `emailProfesor`, `dniProfesor`, `esTutor`, `idCicloTutor`, `telefonoProfesor`, `fechaNacimientoProfesor`, `direccionProfesor`, `ciudadProfesor`, `codigoPostalProfesor`) VALUES (3, 'Javier Ruiz', 'javier@aulapro.com', '44444444D', 1, 2, '611222555', '1978-11-02', 'Paseo del Prado', 'Madrid', '28003');
INSERT IGNORE INTO `modulo_profesor` (`idModulo`, `idProfesor`) VALUES (1, 1);
INSERT IGNORE INTO `modulo_profesor` (`idModulo`, `idProfesor`) VALUES (2, 2);
INSERT IGNORE INTO `modulo_profesor` (`idModulo`, `idProfesor`) VALUES (3, 1);
INSERT IGNORE INTO `modulo_profesor` (`idModulo`, `idProfesor`) VALUES (4, 3);
INSERT IGNORE INTO `estudiantes` (`idEstudiante`, `nombreEstudiante`, `emailEstudiante`, `dniEstudiante`, `idCiclo`, `curso`, `anioEstudio`, `idCurso`, `telefonoEstudiante`, `fechaNacimientoEstudiante`, `direccionEstudiante`, `ciudadEstudiante`, `codigoPostalEstudiante`, `observacionesEstudiante`) VALUES (1, 'Juan Pérez', 'juan@aulapro.com', '55555551E', 1, 'Primero', 1, 1, '655111222', '2000-01-10', 'Calle Estudiante 1', 'Madrid', '28004', 'Excelente rendimiento.');
INSERT IGNORE INTO `estudiantes` (`idEstudiante`, `nombreEstudiante`, `emailEstudiante`, `dniEstudiante`, `idCiclo`, `curso`, `anioEstudio`, `idCurso`, `telefonoEstudiante`, `fechaNacimientoEstudiante`, `direccionEstudiante`, `ciudadEstudiante`, `codigoPostalEstudiante`) VALUES (2, 'Elena Gómez', 'elena@aulapro.com', '55555552E', 1, 'Segundo', 2, 2, '655222333', '1999-04-20', 'Calle Alumno 2', 'Madrid', '28005');
INSERT IGNORE INTO `estudiantes` (`idEstudiante`, `nombreEstudiante`, `emailEstudiante`, `dniEstudiante`, `idCiclo`, `curso`, `anioEstudio`, `idCurso`, `telefonoEstudiante`, `fechaNacimientoEstudiante`, `direccionEstudiante`, `ciudadEstudiante`, `codigoPostalEstudiante`) VALUES (3, 'Miguel Torres', 'miguel@aulapro.com', '55555553E', 2, 'Primero', 1, 3, '655333444', '2001-09-30', 'Avenida Aprendiz', 'Madrid', '28006');
INSERT IGNORE INTO `tutores` (`idTutor`, `nombreTutor`, `emailTutor`, `password`, `idEstudiante`, `must_change_password`) VALUES (1, 'Padre Juan Pérez', 'padre1@aulapro.com', '$2y$10$9nwmzvOe4muwQ9jM5Ryc7.bmaA3Gipm7S4Wnj2S1oiDPnRo1JNcvu', 1, 0);
INSERT IGNORE INTO `tutores` (`idTutor`, `nombreTutor`, `emailTutor`, `password`, `idEstudiante`, `must_change_password`) VALUES (2, 'Madre Elena Gómez', 'madre2@aulapro.com', '$2y$10$9nwmzvOe4muwQ9jM5Ryc7.bmaA3Gipm7S4Wnj2S1oiDPnRo1JNcvu', 2, 0);
INSERT IGNORE INTO `aulas` (`idAula`, `planta`, `numero`, `nombreAula`, `tipoAula`, `capacidad`, `activa`) VALUES (1, 1, 1, 'Aula Magna DAW', 'laboratorio', 30, 1);
INSERT IGNORE INTO `aulas` (`idAula`, `planta`, `numero`, `nombreAula`, `tipoAula`, `capacidad`, `activa`) VALUES (2, 2, 1, 'Taller SMR', 'taller', 25, 1);
INSERT IGNORE INTO `horarios` (`idHorario`, `idCiclo`, `diaSemana`, `horaInicio`, `horaFin`, `idModulo`, `idProfesor`, `idAula`) VALUES (1, 1, 'Lunes', '08:30:00', '10:30:00', 1, 1, 1);
INSERT IGNORE INTO `horarios` (`idHorario`, `idCiclo`, `diaSemana`, `horaInicio`, `horaFin`, `idModulo`, `idProfesor`, `idAula`) VALUES (2, 1, 'Lunes', '10:30:00', '12:30:00', 2, 2, 1);
INSERT IGNORE INTO `horarios` (`idHorario`, `idCiclo`, `diaSemana`, `horaInicio`, `horaFin`, `idModulo`, `idProfesor`, `idAula`) VALUES (3, 2, 'Martes', '08:30:00', '14:30:00', 4, 3, 2);
INSERT IGNORE INTO `aula_tareas` (`idTarea`, `titulo`, `descripcion`, `idModulo`, `idProfesor`, `publicado`, `fechaCreacion`) VALUES (1, 'Práctica JS Avanzada', 'Resuelve ejercicios de JS.', 3, 1, 1, '2026-09-01 10:00:00');
INSERT IGNORE INTO `aula_tareas` (`idTarea`, `titulo`, `descripcion`, `idModulo`, `idProfesor`, `publicado`, `fechaCreacion`) VALUES (2, 'Diseño BD Relacional', 'Crea el modelo E-R.', 2, 2, 1, '2026-09-05 10:00:00');
INSERT IGNORE INTO `aula_entregas` (`idEntrega`, `idTarea`, `idEstudiante`, `respuesta`, `nota`, `estado`, `fechaEntrega`, `comentarioCalificacion`) VALUES (1, 1, 2, 'Adjunto solución JS.', 8.5, 'corregida', '2026-09-30 10:00:00', 'Buen trabajo con las Promesas.');
INSERT IGNORE INTO `aula_entregas` (`idEntrega`, `idTarea`, `idEstudiante`, `respuesta`, `nota`, `estado`, `fechaEntrega`, `comentarioCalificacion`) VALUES (2, 2, 1, 'Diagrama en PDF adjunto.', 9.0, 'corregida', '2026-10-09 12:00:00', 'Excelente normalización.');
INSERT IGNORE INTO `retos` (`idReto`, `nombreReto`, `fechaInicio`, `fechaFin`, `horasReto`) VALUES (1, 'Crear E-Commerce desde cero', '2026-10-01', '2026-12-20', 100);
INSERT IGNORE INTO `modulo_reto` (`idReto`, `idModulo`) VALUES (1, 1);
INSERT IGNORE INTO `modulo_reto` (`idReto`, `idModulo`) VALUES (1, 2);
INSERT IGNORE INTO `anuncios` (`idAnuncio`, `titulo`, `mensaje`, `dirigidoA`, `fechaExpiracion`, `fechaAnuncio`) VALUES (1, 'Bienvenidos al Curso 2025-2026', 'Esperamos que este año esté lleno de aprendizaje.', 'todos', '2026-12-31', '2026-09-01');
INSERT IGNORE INTO `blog_posts` (`idPost`, `titulo`, `slug`, `resumen`, `contenido`, `publicado`, `destacado`, `fechaPublicacion`) VALUES (1, 'Apertura del Centro Formativo', 'apertura', 'Comienza un nuevo año con gran ilusión.', 'El día 15 damos el pistoletazo de salida...', 1, 1, '2026-09-01');
INSERT IGNORE INTO `eventos` (`idEvento`) VALUES (1);
INSERT IGNORE INTO `dispositivos` (`idDispositivo`, `nombreDispositivo`, `numeroSerie`, `estadoDispositivo`) VALUES (1, 'Portátil Dell Latitude', 'DL-2025-001', 'disponible');
INSERT IGNORE INTO `dispositivos` (`idDispositivo`, `nombreDispositivo`, `numeroSerie`, `estadoDispositivo`) VALUES (2, 'Portátil Lenovo ThinkPad', 'LN-2025-002', 'prestado');
INSERT IGNORE INTO `prestamos` (`idPrestamo`, `idEstudiante`, `numeroSerie`, `fechaPrestamo`, `estadoPrestamo`) VALUES (1, 1, 'LN-2025-002', '2026-09-15', 'en curso');
INSERT IGNORE INTO `fp_empresas` (`idEmpresa`, `nombre`, `cif`, `activo`) VALUES (1, 'Tech Solutions SL', 'B12345678', 1);
INSERT IGNORE INTO `fp_empresas` (`idEmpresa`, `nombre`, `cif`, `activo`) VALUES (2, 'DataCorp Innovation', 'B87654321', 1);
INSERT IGNORE INTO `fct` (`idFCT`, `idEstudiante`, `idCiclo`, `empresa`, `idEmpresa`, `tutorEmpresa`, `emailTutorEmpresa`, `telefonoEmpresa`, `ciudadEmpresa`, `fechaInicio`, `fechaFin`, `horasTotales`, `horasRealizadas`, `idProfesorTutor`, `fase`) VALUES (1, 2, 1, 'Tech Solutions SL', 1, 'Laura RRHH', 'laura.rrhh@aulapro.com', '911222333', 'Madrid', '2027-03-15', '2027-06-15', 400, 120, 1, 1);
INSERT IGNORE INTO `resultados_aprendizaje` (`idRA`, `idModulo`, `codigo`, `descripcion`, `porcentaje`) VALUES (1, 1, 'RA1', 'Programa aplicaciones básicas.', 50);
INSERT IGNORE INTO `resultados_aprendizaje` (`idRA`, `idModulo`, `codigo`, `descripcion`, `porcentaje`) VALUES (2, 1, 'RA2', 'Usa POO en Java.', 50);
INSERT IGNORE INTO `criterios_evaluacion` (`idCE`, `idRA`, `codigo`, `descripcion`) VALUES (1, 1, 'CE1.a', 'Declara variables y estructuras de control.');
INSERT IGNORE INTO `criterios_evaluacion` (`idCE`, `idRA`, `codigo`, `descripcion`) VALUES (2, 2, 'CE2.a', 'Instancia clases y usa herencia.');
INSERT IGNORE INTO `calificaciones_ce` (`idCalificacionCE`, `idEstudiante`, `idCE`, `nota`) VALUES (1, 1, 1, 9.5);
INSERT IGNORE INTO `calificaciones_modulos` (`idCalificacion`, `idEstudiante`, `idModulo`, `nota_1ev`, `estado_1ev`) VALUES (1, 1, 1, 8.5, 'CO');
INSERT IGNORE INTO `categorias_gasto` (`idCategoria`) VALUES (1);
INSERT IGNORE INTO `categorias_gasto` (`idCategoria`) VALUES (2);
INSERT IGNORE INTO `gastos` (`idGasto`, `concepto`, `importe`, `idCategoria`) VALUES (1, 'Compra de 5 proyectores', 1500.0, 2);
INSERT IGNORE INTO `pagos` (`idPago`, `idEstudiante`, `monto`, `fechaPago`, `tipoPago`, `estadoComprobante`) VALUES (1, 1, 2500.0, '2026-08-15', 'matricula', 'aprobado');
INSERT IGNORE INTO `pagos` (`idPago`, `idEstudiante`, `monto`, `fechaPago`, `tipoPago`, `estadoComprobante`) VALUES (2, 2, 2500.0, '2026-08-20', 'matricula', 'aprobado');
INSERT IGNORE INTO `pre_matriculas` (`idPreMatricula`, `dni`, `nombre`, `apellidos`, `email`, `telefono`, `idCiclo`, `curso`, `estado`, `fechaSolicitud`) VALUES (1, '77777771Z', 'Nuevo Alumno 1', 'Martín Silva', 'nuevo1@aulapro.com', '677111222', 1, 'Primero', 'pendiente', '2026-08-01 10:00:00');
INSERT IGNORE INTO `pre_matriculas` (`idPreMatricula`, `dni`, `nombre`, `apellidos`, `email`, `telefono`, `idCiclo`, `curso`, `estado`, `fechaSolicitud`) VALUES (2, '77777772Z', 'Nuevo Alumno 2', 'García López', 'nuevo2@aulapro.com', '677222333', 2, 'Segundo', 'admitido', '2026-08-02 11:30:00');
INSERT IGNORE INTO `asistencias` (`idAsistencia`, `idEstudiante`, `idModulo`, `idProfesor`, `fecha`, `estado`, `observacion`, `fechaRegistro`) VALUES (1, 1, 1, 1, '2026-10-01', 'falta', 'No asistió a clase', '2026-10-01 14:00:00');
INSERT IGNORE INTO `asistencias` (`idAsistencia`, `idEstudiante`, `idModulo`, `idProfesor`, `fecha`, `estado`, `observacion`, `fechaRegistro`) VALUES (2, 2, 2, 2, '2026-10-02', 'retraso', 'Llegó 15 min tarde', '2026-10-02 14:00:00');
INSERT IGNORE INTO `asistencias` (`idAsistencia`, `idEstudiante`, `idModulo`, `idProfesor`, `fecha`, `estado`, `fechaRegistro`) VALUES (3, 3, 4, 3, '2026-10-03', 'falta_justificada', '2026-10-03 14:00:00');
INSERT IGNORE INTO `justificaciones_falta` (`idJustificacion`, `idAsistencia`, `idEstudiante`, `motivo`, `estado`, `idProfesorResuelve`, `fechaSolicitud`, `fechaResolucion`) VALUES (1, 3, 3, 'Cita médica adjunta.', 'aprobada', 3, '2026-10-03 15:00:00', '2026-10-04 09:00:00');
INSERT IGNORE INTO `justificaciones_falta` (`idJustificacion`, `idAsistencia`, `idEstudiante`, `motivo`, `estado`, `fechaSolicitud`) VALUES (2, 1, 1, 'Problema de transporte.', 'pendiente', '2026-10-02 10:00:00');
INSERT IGNORE INTO `reclamaciones` (`idReclamacion`, `idEstudiante`, `idProfesor`, `emisor_rol`, `asunto`, `descripcion`, `fecha`, `estadoReclamacion`, `leido`) VALUES (1, 1, 1, 'estudiante', 'Revisión nota Tarea 1', 'Creo que el ejercicio 3 está correcto.', '2026-10-15 10:00:00', 'abierta', 0);
INSERT IGNORE INTO `chat_conversaciones` (`id`, `user_a_rol`, `user_a_id`, `user_b_rol`, `user_b_id`, `last_message_at`) VALUES (1, 'estudiante', 1, 'profesor', 1, '2026-10-16 10:00:00');
INSERT IGNORE INTO `chat_mensajes` (`id`, `conversacion_id`, `emisor_rol`, `emisor_id`, `contenido`, `leido`, `fecha`) VALUES (1, 1, 'estudiante', 1, 'Hola profesor, ¿cuándo se publica la nota final?', 1, '2026-10-16 09:50:00');
INSERT IGNORE INTO `chat_mensajes` (`id`, `conversacion_id`, `emisor_rol`, `emisor_id`, `contenido`, `leido`, `fecha`) VALUES (2, 1, 'profesor', 1, 'Se publicará mañana por la tarde. Saludos.', 0, '2026-10-16 10:00:00');

SET FOREIGN_KEY_CHECKS=1;
