import 'dart:convert';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../features/chat/data/chat_repository.dart';
import '../api/api_client.dart';
import '../auth/auth_state.dart';
import '../router/app_router.dart';
import '../router/home_shell.dart';

/// Must match the `channel_id` firebase_helper.php sends in every push's
/// `android.notification` block, so background/terminated tray entries (FCM
/// auto-displayed) and foreground ones (shown by us via flutter_local_notifications
/// below) land in the same, identically-named Android channel.
const _kAndroidChannelId = 'default_channel';
final String _kAndroidChannelName = dotenv.env['APP_NAME'] ?? 'App';

/// Top-level (required by the plugin) — runs in a separate isolate when a
/// data message arrives while the app is backgrounded/terminated. Nothing to
/// do here beyond letting the system show the notification tray entry;
/// tap-handling lives in [NotificationsService._handleTapData] instead.
@pragma('vm:entry-point')
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {}

/// Wraps Firebase Cloud Messaging end to end: permission request, token
/// registration against /api/v1/fcm-token.php, refresh handling, foreground
/// display, and tap-to-deep-link. Every step is best-effort — this app has no
/// android/app/google-services.json committed (per-developer, generated by
/// registering the app in the Firebase console), so `Firebase.initializeApp`
/// throws until that one-time manual step is done. That failure — and any
/// other push-related failure — must never take down the rest of the app,
/// so everything here is wrapped and swallowed rather than propagated.
class NotificationsService {
  NotificationsService(this._ref);
  final Ref _ref;
  bool _started = false;
  final _localNotifs = FlutterLocalNotificationsPlugin();

  Future<void> init() async {
    if (_started) return;
    _started = true;

    try {
      await Firebase.initializeApp();
    } catch (_) {
      return; // no google-services.json yet — push stays silently off
    }

    try {
      await _initLocalNotifications();

      FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
      final messaging = FirebaseMessaging.instance;
      await messaging.requestPermission(alert: true, badge: true, sound: true);

      final token = await messaging.getToken();
      if (token != null) await _registerToken(token);
      messaging.onTokenRefresh.listen(_registerToken);

      // FCM only auto-displays a tray notification while backgrounded/
      // terminated — with the app foregrounded (the common case while
      // actively using it) nothing appears unless shown ourselves here.
      FirebaseMessaging.onMessage.listen(_showForegroundNotification);

      FirebaseMessaging.onMessageOpenedApp
          .listen((m) => _handleTapData(m.data));
      final initial = await messaging.getInitialMessage();
      if (initial != null) _handleTapData(initial.data);
    } catch (_) {
      // best-effort — a push setup failure must never break the app
    }
  }

  Future<void> _initLocalNotifications() async {
    const androidSettings =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    const iosSettings = DarwinInitializationSettings();
    await _localNotifs.initialize(
      settings: const InitializationSettings(
          android: androidSettings, iOS: iosSettings),
      onDidReceiveNotificationResponse: (response) {
        final payload = response.payload;
        if (payload == null) return;
        try {
          final data = jsonDecode(payload) as Map<String, dynamic>;
          _handleTapData(data);
        } catch (_) {
          // malformed/old payload — ignore rather than crash on tap
        }
      },
    );

    // Android 8+ requires the channel to exist before a notification can be
    // posted into it; iOS has no channel concept and ignores this call.
    await _localNotifs
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(AndroidNotificationChannel(
          _kAndroidChannelId,
          _kAndroidChannelName,
          importance: Importance.high,
        ));
  }

  Future<void> _showForegroundNotification(RemoteMessage message) async {
    // Bumped regardless of whether there's a `notification` payload to show
    // a tray entry for — a chat screen open on this exact conversation
    // should refresh immediately either way, not just when a popup fires.
    if (message.data['type'] == 'chat_message') {
      final convId = int.tryParse(message.data['conv_id']?.toString() ?? '');
      if (convId != null) {
        _ref.read(chatMessagePushProvider.notifier).state = convId;
      }
    }

    final notif = message.notification;
    if (notif == null) return; // data-only message — nothing to surface
    try {
      await _localNotifs.show(
        id: message.hashCode,
        title: notif.title,
        body: notif.body,
        notificationDetails: NotificationDetails(
          android: AndroidNotificationDetails(
            _kAndroidChannelId,
            _kAndroidChannelName,
            importance: Importance.high,
            priority: Priority.high,
          ),
          iOS: const DarwinNotificationDetails(),
        ),
        payload: jsonEncode(message.data),
      );
    } catch (_) {
      // best-effort — a failed foreground popup must never break the app
    }
  }

  Future<void> _registerToken(String token) async {
    final session = _ref.read(sessionControllerProvider).value;
    if (session == null) return;
    try {
      await _ref
          .read(apiClientProvider)
          .post('/fcm-token.php', data: {'token': token});
    } catch (_) {
      // registration failing shouldn't block anything else — will retry
      // next app start or next onTokenRefresh
    }
  }

  void _handleTapData(Map<String, dynamic> data) {
    final type = data['type'] as String?;
    final session = _ref.read(sessionControllerProvider).value;
    if (type == null || session == null) return;

    final router = _ref.read(routerProvider);
    final route = homeRouteForType(type);
    if (route != null) {
      router.go('/home');
      router.push(route);
      return;
    }

    final tabIndex = homeTabIndexForType(type, session.role);
    if (tabIndex != null) {
      _ref.read(homeTabIndexProvider.notifier).state = tabIndex;
    }
    router.go('/home');
  }
}

final notificationsServiceProvider =
    Provider<NotificationsService>((ref) => NotificationsService(ref));
