import java.util.Properties
import java.io.FileInputStream

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// Release signing — reads from android/key.properties, which is per-developer
// and gitignored (see android/.gitignore: key.properties, *.keystore, *.jks)
// same reasoning as google-services.json below: never commit a real signing
// key, so this must degrade gracefully rather than break every build until
// the one-time keystore-generation step is done. Play Store REJECTS any
// upload signed with the debug keystore — this is what the release build
// falls back to until key.properties exists, so it's fine for local
// `flutter build apk/appbundle` testing but NOT submittable as-is.
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

android {
    namespace = "com.aulapro.aulapro_mobile"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        // Required by flutter_local_notifications (used for foreground push
        // display) — its Android implementation calls java.time APIs that
        // need desugaring support on API levels below 26.
        isCoreLibraryDesugaringEnabled = true
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.aulapro.aulapro_mobile"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = flutter.minSdkVersion
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    signingConfigs {
        if (keystorePropertiesFile.exists()) {
            create("release") {
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
                storeFile = file(keystoreProperties["storeFile"] as String)
                storePassword = keystoreProperties["storePassword"] as String
            }
        }
    }

    buildTypes {
        release {
            // Real release signing once key.properties exists (see above);
            // falls back to the debug keystore otherwise, so
            // `flutter run --release` still works for local testing before
            // that one-time setup is done. A debug-signed build must never
            // be uploaded to the Play Console — it will be rejected.
            signingConfig = if (keystorePropertiesFile.exists()) {
                signingConfigs.getByName("release")
            } else {
                signingConfigs.getByName("debug")
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    // Backs isCoreLibraryDesugaringEnabled above.
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")
}

flutter {
    source = "../.."
}

// Applied conditionally, not in the plugins{} block above: this repo doesn't
// commit google-services.json (it's per-developer, generated by registering
// this app in the Firebase console), so requiring it unconditionally would
// break every build until that one-time manual step is done. Push
// notifications simply no-op at runtime (see NotificationsService) until the
// file is dropped in at android/app/google-services.json.
if (file("google-services.json").exists()) {
    apply(plugin = "com.google.gms.google-services")
}
